global:
  imageRegistry: "docker.io"

defaults:
  replicaCount: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  serviceAccountName: "default"
  automountServiceAccountToken: true
  imagePullSecrets:
    - name: "default-secret"
  volumes: []
  securityContext:
    fsGroup: 1000
  containers:
    - name: "default-container"
      image:
        repository: "example/default"
        tag: "latest"
        pullPolicy: "IfNotPresent"
      ports: []
      resources: {}
      env: []
      args: []
      volumeMounts: []
      securityContext: {}

deployments: []

service: []
networkPolicies: []
