# Default values for my-generic-chart.
deployment:
  replicaCount: 2
  strategy:
    minReadySeconds: 10
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  serviceAccountName: default
  automountServiceAccountToken: true
  volumes:
    - name: "placeholder-vol"
      configMap:
        name: "placeholder-config"

containers:
  - name: "" # Optionaler Wert; wenn leer, wird der Name aus dem Image-Repository abgeleitet
    image:
      repository: "" # Der Benutzer muss dies angeben
      tag: "" # Der Benutzer muss dies angeben
      pullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
        name: http
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080

service:
  type: ClusterIP
  port: 8080
