apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.deployment.strategy.type }}
    minReadySeconds: {{ .Values.deployment.strategy.minReadySeconds }}
  template:
    metadata:
      labels: {{ include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ default (include "common.names.fullname" .) .Values.deployment.serviceAccountName }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
    containers:
      {{- range .Values.containers }}
      - name: {{ default (include "common.names.fullname" .) .name | quote }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ default $.Values.defaultContainer.image.pullPolicy .image.pullPolicy }}
        ports:
          {{- toYaml (default $.Values.defaultContainer.ports .ports) | nindent 12 }}
        resources:
          {{- toYaml (default $.Values.defaultContainer.resources .resources) | nindent 12 }}
        livenessProbe:
          {{- toYaml (default $.Values.defaultContainer.livenessProbe .livenessProbe) | nindent 12 }}
        readinessProbe:
          {{- toYaml (default $.Values.defaultContainer.readinessProbe .readinessProbe) | nindent 12 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.deployment.volumes | nindent 8 }}
