{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . | default (include "common.names.fullname" $.Values.defaults) }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .replicaCount | default $.Values.defaults.replicaCount }}
  minReadySeconds: {{ .minReadySeconds | default $.Values.defaults.minReadySeconds }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    {{- with .strategy }}
    type: {{ .type | default $.Values.defaults.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .rollingUpdate.maxSurge | default $.Values.defaults.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .rollingUpdate.maxUnavailable | default $.Values.defaults.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels: {{ include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .serviceAccountName | default $.Values.defaults.serviceAccountName }}
      automountServiceAccountToken: {{ .automountServiceAccountToken | default $.Values.defaults.automountServiceAccountToken }}
      imagePullSecrets:
        {{- if .imagePullSecrets }}
        {{- toYaml .imagePullSecrets | nindent 10 }}
        {{- else }}
        {{- toYaml $.Values.defaults.imagePullSecrets | nindent 10 }}
        {{- end }}
      securityContext:
        fsGroup: {{ .securityContext.fsGroup | default $.Values.defaults.securityContext.fsGroup }}
      containers:
        {{- range .containers }}
        - name: {{ .name | default (printf "%s-container" $.Release.Name) }}
          image: {{- $registry := default $.Values.global.imageRegistry }}
                {{- $image := .image | default $.Values.defaults.containers.0.image }}
                {{ printf "%s/%s:%s" $registry $image.repository $image.tag }}
          imagePullPolicy: {{ .image.pullPolicy | default $.Values.defaults.containers.0.image.pullPolicy }}
          ports:
            {{- toYaml .ports | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          env:
            {{- toYaml .env | nindent 12 }}
          args:
            {{- toYaml .args | nindent 12 }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .volumes }}
        {{- toYaml .volumes | nindent 8 }}
        {{- else }}
        {{- toYaml $.Values.defaults.volumes | nindent 8 }}
        {{- end }}
{{- end }}
