{{- if .Values.networkPolicies }}
{{- range .Values.networkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
spec:
  podSelector:
    matchLabels: {{ toYaml .podSelector.matchLabels | nindent 4 }}
  policyTypes:
    {{- if .ingress }}
    - Ingress
    {{- end }}
    {{- if .egress }}
    - Egress
    {{- end }}
  {{- if .ingress }}
  ingress:
    {{- range .ingress }}
    - from:
        {{- range .from }}
        - podSelector:
            matchLabels: {{ toYaml .podSelector.matchLabels | nindent 12 }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .egress }}
  egress:
    {{- range .egress }}
    - to:
        {{- range .to }}
        - podSelector:
            matchLabels: {{ toYaml .podSelector.matchLabels | nindent 12 }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
